### ISSUE TITLE
Improvement ideas for website

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#152]
Container for all ideas for improvements for websites - we'll take this feedback and use it to inform design choices so feel free to dump any ideas in here

**Comment by sjmog** [comment]
Lots of calls for icons @rubenkostucki - my personal angle on this is to keep icons to a minimum, and use them only when absolutely necessary (tbh that's much of my design philosophy in a single sentence). Icons as decoration implies the page aesthetic is the big deal, when aesthetic _must_ serve a function (less important in print than on the web)

**Comment by rubenkostucki** [comment]
I don't think we should go over the top but currently don't have any or
much. I think icons is what makes the content much more appealing. Also, an
image speaks a thousand words; icons can dramatically accelerate the speed
at which one gathers information, especially when in a list format = that's
the function. The first point on
http://www.smashingmagazine.com/2009/03/03/how-to-use-icons-to-support-content-in-web-design/
clarifies this (note that there's a million article for and against icons,
so not making this a reference!).
I honestly think it's really valuable

**Comment by sjmog** [comment]
Icons are an odd one @rubenkostucki - I hear you with the 'million articles for and against', but in my experience doing web design it's been a linear set of trends about icons:

- 2007 (iPhone introduction) icons are GREAT! They're small and tappable and communicate across language barriers.
- 2009 (the article you posted) icons should be on the web, they make boring data FUN! We should make them colourful and 3D (skeuomorphic) because people just love colours. Apps start substituting labels for icons on the bottom bars.
- c. 2010 (line icons) icons should be represented as clean lines, because that makes them more aesthetically lightweight. They'll sink into the user subconscious and people will just _know_ what they are. Tapbot and Twitter update their apps to use line icons.
- c. 2012 'research' appears suggesting that line icons require more intensive brain engagement to recognise than block icons. It's mostly nonsense but everyone goes mad about how line icons are the devil.
- 2013 (iOS6) icons shouldn't be skeumorphs, they should be abstract representations of functionality. Jonny Ive redesigns iOS to use icons in a more minimal way. Web designers cry b/c Ive insists on using line icons.
- 2014 Icons are only useful when paired with a label to underline what they mean. The idea that you can guess that a wonky star means 'community (not personal) favourites' becomes laughable.
- 2015 The whole community starts asking 'is there actually any user benefit to using icons anyway?', as there's never actually been any hard evidence they improve usability.

I would dearly love to support each of these bullets with an article, but I've historically sucked at recording the things I read. That's a lesson for me - but I'd be inclined to hold off on icons at the moment until we have evidence that people are literally _not clicking_ 'Facebook' because they don't understand that will take them to Facebook.
