### ISSUE TITLE
Refactor CSS/HTML

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#207]

**Comment by pitchinvasion** [comment]
Make sure this addresses #323

**Comment by pitchinvasion** [comment]
Also once it's done we'll update bower and then update all the other sites with the new goodness

**Comment by roidriscoll** [comment]
Hey buddy,

I noticed some of the spacing on the manifesto looks a bit off - probably due to the fact that I think we missed the leader/header combo during the vertical rhythm exercise. I think this looks better:
<img width="368" alt="screen shot 2015-08-12 at 10 56 05" src="https://cloud.githubusercontent.com/assets/2243253/9221285/2b1a7104-40e1-11e5-82a6-a99887acad72.png">

I took 0.5rem off the line height of the h3 and added it to the h4 instead. Hope it helps :)

**Comment by sjmog** [comment]
Much nicer dude :+1: 

Did you do this on this branch?

**Comment by roidriscoll** [comment]
Sorry, I should have clarified - that was just done in the browser because I didn't want to mess with what you're doing!

**Comment by pitchinvasion** [comment]
Once this is done don't forget to make the elements page public (I think we definitely want to show it off now it looks all good), and then let jordan know as he wants to send the designers who are pitching to us it so they can see what we're up to on the web side of things

**Comment by pitchinvasion** [comment]
@sjmog is crazy busy at the moment so this is going into the backlog
