### ISSUE TITLE
Add new dates for 2016 courses

### ISSUE THREAD

**Issue by jordanpoulton** [makersacademy/website#445]
Make sure that course dates through 2016 are listed. We're only showing 3 right now.

**Comment by pitchinvasion** [comment]
These will also need to be updated in Pipedrive as well

**Comment by tansaku** [comment]
@jordan @pitchinvasion - in the first instance is this just a copy change.  

@jordanpoulton if you know the dates can you just make a pull request?

ben and I reviewed and it seems like you just need to add the additional dates in this yml file:

https://github.com/makersacademy/website/blob/master/data/intakes.yml

you can do this locally and submit a pull request.  We can do this if you are crazy busy, but like I said yesterday I really want to enable you to make minor copy changes like this that we can then review

**Comment by tansaku** [comment]
@jordanpoulton for reference - here are the dates that are being used in applications:

https://github.com/makersacademy/applications/blob/master/lib/data/intakes.yml

@pitchinvasion - I guess there's a discussion to have about DRYing these out so that all the sites have access to the latest data ...
